"""Add chat_messages table

Revision ID: 6497f04209cc
Revises: 2e2a88b0c43d
Create Date: 2026-04-16 09:58:28.016321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6497f04209cc'
down_revision: Union[str, Sequence[str], None] = '2e2a88b0c43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('sender_id', sa.Integer(), nullable=False),
                    sa.Column('recipient_id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['recipient_id'], ['users.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['sender_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_chat_messages_recipient_id'),
                    'chat_messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_sender_id'),
                    'chat_messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_sender_id'),
                  table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_recipient_id'),
                  table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
